BUNDLE_NAME = HATEPreferences
HATEPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
HATEPreferences_FRAMEWORKS = UIKit
HATEPreferences_PRIVATE_FRAMEWORKS = Preferences
HATEPreferences_INSTALL_PATH = /Library/PreferenceBundles
HATEPreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
